### ISSUE TITLE
[1.20.1] Game crashes when pressing morph key.

### ISSUE THREAD

**Issue by KajesLorian** [ToCraft/woodwalkers-mod#100]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

3.6.2

### Woodwalkers version

4.4.3

### CraftedCore version

4.2.3

### Modloader version

Neoforge 47.1.105

### The latest.log file

https://gist.github.com/KajesLorian/a9e1864c8b757227f4fa47535138fe5f

### Issue description

Game crashes completely out when pressing the choose second shape button.

### Steps to reproduce

1. Start game
2. Go into world
3. Press ` key
4. Crash

**Comment by ToCraft** [comment]
Nvm, please just install the NeoForge version of SmartBrainLib, when using NeoForge. (It's a dependency of Occultism.)
