### ISSUE TITLE
you can no longer start a single player world and with craftedcore version 4.3 the game crashes

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#103]
### Mod loader

Neoforge

### Minecraft version

1.20.6

### Woodwalkers version

4.5.1

### CraftedCore version

4.3

### Modloader version

Neoforge

### The latest.log file

No Answer

### Issue description

hi I wanted to play the mod again after a few versions but when I tried again and again to start a single player world I kept getting kicked out and constantly ended up in the server selection where I didn't want to go. With this mod it's so to speak no longer possible single player to play
![Screenshot 18 06 2024 14_46_18](https://github.com/ToCraft/woodwalkers-mod/assets/87422017/255d8ffd-ec3d-45d9-9dec-05e96e62ff11) I believe that it also occurs with all modloaders, but I only tested it with neoforge and with craftedcore version 4.3 the game crashes

### Steps to reproduce

1.install crafted core
2.install wodwalkers
3.start minecraft
4.create or start a single player world

### Other

No Answer

**Comment by ToCraft** [comment]
should be fixed as of the newest craftedcore version (4.3.1). Please reopen the issue, if it still doesn't work for you.
