### ISSUE TITLE
Dolphens Burn in Daylight when they shouldnt

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#104]
### Mod loader

Fabric

### Minecraft version

1.20.6

### Woodwalkers version

4.6

### CraftedCore version

4.3.1

### Modloader version

0.15.11

### The latest.log file

file:///home/nathaniel/Desktop/IMPORTANT%20DONT%20DELETE/Minecraft%20stuff/instances/1.20.6/.minecraft/logs/latest.log

### Issue description

Dolphens Burn in daylight when they shouldnt

### Steps to reproduce

Start Game 
Morph into Dolphen in Survivel
You Will Burn in Daylight

**Comment by ToCraft** [comment]
fixed as of Walkers 5
