### ISSUE TITLE
(1.21) Allow Players to eat items that correspond to the mob's favorite foods, regardless if inedible or not to the player's base form

### ISSUE THREAD

**Issue by Inonedn** [ToCraft/woodwalkers-mod#105]
### Describe your idea, include images if necessary

Due to there being a food tag, and a mob's favorite foods can be controlled by tags, it could probably be easy to impelment. For example, as a strider, you can eat a Warped Fungus, or as an Axolotl, you can eat a bucket of tropical fish, returning a bucket

**Comment by ToCraft** [comment]
Hm, I could find the Food Tag in the Minecraft Wiki... Are you referring to some mod?
