### ISSUE TITLE
Bats

### ISSUE THREAD

**Issue by Golden-Dragon161** [ToCraft/woodwalkers-mod#107]
I was just trying this mod in creative with many mobs, one of them was the bat, I switched to survival with many mobs in many situations, and now one of them was about being surrounded by hostiles, The hostile mobs attacked me in bat form, which I think is weird as they do not attack vanilla bats.

I suggest making hostile mobs neutral toward passive mob forms (passive till attacked),
I also suggest removing other requirements of neutrality to the mob forms, as it isn't logical (in the Minecraft sense) for bats, cows, sheep, etc to be wearing gold armour (requirement of neutrality of piglins)

This is nothing but a suggestion, it is a great mod, but I would appreciate it if you could implement such mechanics to the mod
I also apologise as I am not a modder so I can not provide you with code to this idea

Please excuse my poor language skills, as english is not my first language
Thank you

**Comment by ToCraft** [comment]
Alright, I'll do my best to integrate your suggestions :D
I'll probably add a config option to toggle the "new way of handling neutrality", too.

**Comment by Golden-Dragon161** [comment]
Thank you for taking this suggestion
I like your mod and probably will continue playing with it in newer versions
