### ISSUE TITLE
Alex's Mobs integration

### ISSUE THREAD

**Issue by Astral-Haze** [ToCraft/woodwalkers-mod#110]
### Describe your idea, include images if necessary

For mobs from Alex's Mobs to attack/behave towards transformed players as they do to the real mobs, e.g. flies attacking zombies and whales attacking squid

**Comment by ToCraft** [comment]
Hey, great idea!

Can you send me a list of which mob attacks which? I'm not that used to Alexs Mobs.

**Comment by Astral-Haze** [comment]
https://github.com/AlexModGuy/AlexsMobs/tree/1.20/src/main/resources/data/alexsmobs/tags/entity_types
most? of them are in here as tags, although there's at least one I notice missing, being the bunfungus who attacks some mobs
Bunfungus may be copying the iron golem's list? it seems to be the same, or nearly the same, including some from alex's mobs: Cave centipede, guster, skreecher, murmur, bone serpent, dropbear, crimson mosquito, enderiophage, farseer, mimicube, skelewag, warped mosco, rocky roller, void worm

Although, it seems iron golems already will attack the player as those mobs from the mod, but the bunfungus will not
