### ISSUE TITLE
Allow selectors for `switchShape` command

### ISSUE THREAD

**Issue by shap-po** [ToCraft/woodwalkers-mod#115]
### Describe your idea, include images if necessary

For example:
`/walkers switchShape @s @e[type=!player,limit=1,sort=nearest]` will morph the player into the nearest mob

**Comment by ToCraft** [comment]
implemented as of https://github.com/ToCraft/woodwalkers-mod/pull/122

**Comment by shap-po** [comment]
Thanks a lot!
