### ISSUE TITLE
Huge FPS loss when in water

### ISSUE THREAD

**Issue by Marketooo** [ToCraft/woodwalkers-mod#130]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

walkers-5.2

### CraftedCore version

craftedcore-5.5

### Modloader version

47.3.7

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16825580/latest.log)

### Issue description

I am hosting a survival world where i'm morphed as a Skeleton and  my friend is a human.
Whenever I get into a pool of water, >everyone starts to lag<. (and by that i mean we both go from a solid 120+ FPS to 1 - 3)
What's also curious is that it happens only when someone is morphed in survival and is in water. (not even swimming, just standing there does it) It also depends on where you're looking at, whenever I look up/at the sky or go back into Creative Mode, our FPS seem to be fine again.

So far I've tested only as a Creeper, Zombie and a Skeleton in an ocean and river and this has happened everytime.

Here's an example of me switching back and forth into creative and survival while in water
https://github.com/user-attachments/assets/235f75c3-0930-494e-982e-7340eb4bfb45

And here's me showing how looking up stops the lag
https://github.com/user-attachments/assets/b94af588-b573-4f82-945f-4d5ed16a4e35

### Steps to reproduce

In a world, morph into a mob (for ex: Skeleton, Zombie, Creeper)
Go into Survival Mode
Jump in a large pool of water (lake, ocean, river....)
Swim, (Underwater or not, doesn't really matter) move your camera around

**Comment by ToCraft** [comment]
Can you test it again with only  woodwalkers & CraftedCore installed?
If it works, it's a mod incompatibility. Since I don't know what mods you installed, you'll have to manually go through the mods and sort the unrelated ones out (so only woodwalkers & the mod it doesn't work with remain).

**Comment by Marketooo** [comment]
It is indeed a mod incompatibility, after further testing it seems that this bug occurs only when "Siren Head: The Arrival" is installed, I've only tested with Siren_head v1.1.4-1.20.1, not the other mod versions

**Comment by ToCraft** [comment]
Alright, since "Siren Head: The Arrival" is closed source, I can't create a PR or something similiar to fix it.
You might report it to them, it's probably an issue in their AI logic.
