### ISSUE TITLE
add support for Craziness Awakened 

### ISSUE THREAD

**Issue by FullMetalMaster** [ToCraft/woodwalkers-mod#131]
### Describe your idea, include images if necessary

https://www.curseforge.com/minecraft/mc-mods/craziness-awakened

Add flying to flying mobs birds and moths etc

**Comment by ToCraft** [comment]
Sure, I can do that. Please specify the exact entity ids (e.g. `minecraft:wolf`) and what traits I should add to them.

**Comment by ToCraft** [comment]
Implemented as of 4e70ca99e9e74fcd68969a9d8ad8502fa0a6884f
