### ISSUE TITLE
add abilities for flying mobs from exotic birds

### ISSUE THREAD

**Issue by Tikalian-coconut** [ToCraft/woodwalkers-mod#133]
### Describe your idea, include images if necessary

currently the exotic birds mod have plenty of birds that are cool looking, yet they have no flying abilities which is weird considering their birds :/
is it possible to add it please?

**Comment by ToCraft** [comment]
Sure. Can you give me an exact list of every id for the flying mobs? (e.g. `minecraft:bat`)

**Comment by Tikalian-coconut** [comment]
sure!
`exoticbirds:magpie` 
`exoticbirds:bluejay`
`exoticbirds:booby`
`exoticbirds:cardinal`
`exoticbirds:pigeon`
`exoticbirds:macaw`
`exoticbirds:hummingbird`
`exoticbirds:cockatoo`
`exoticbirds:crane`
`exoticbirds:owl`
`exoticbirds:pelican`
`exoticbirds:robin`
`exoticbirds:flamingo`
`exoticbirds:duck`
`exoticbirds:gouldianfinch`
`exoticbirds:gull`
`exoticbirds:heron`
`exoticbirds:kookaburra`
`exoticbirds:lyrebird`
`exoticbirds:peafowl`
`exoticbirds:swan`
`exoticbirds:toucan`
i think it's all birds that fly.. there are a few i'm not sure about so i did some research and fixed the list, now it's complete.

**Comment by ToCraft** [comment]
Implemented as of ea851be580f2494f15e96624e30a83d0f6307c46 :D

**Comment by Tikalian-coconut** [comment]
how do i add it to the 1.20.1 version? (sorry I don't know how to add the fix to the version i have)
is there a way?

**Comment by ToCraft** [comment]
It will be available with the next update, you only need to update once I publish it

**Comment by Tikalian-coconut** [comment]
i will update for sure!
keep up with your work it's awesome
