### ISSUE TITLE
Crash at launch, with WoodWalkers 5.3

### ISSUE THREAD

**Issue by Dralaon** [ToCraft/woodwalkers-mod#135]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Woodwalkers version

5.3

### CraftedCore version

5.5

### Modloader version

0.16.5

### The latest.log file

[2024-10-02-1.log](https://github.com/user-attachments/files/17219796/2024-10-02-1.log)

### Issue description

Title.
Working fine with WoodWalkers 5.2

idk if is a incompatibility with something, have 300+ mods in it.

### Steps to reproduce

Start the game > Crash.

**Comment by Tikalian-coconut** [comment]
I have the same problem here, but with the forge version (still 1.20.1), there's no crash reports so can't really put it there cuz it just crashes and says "error 1" and does nothing else.
It worked fine with previous versions (i used the 4.6 version of walkers) and i have around 168 mods and don't know why it just crashes without saying anything
maybe it's an issue with the Crafted Core 5.5 version that isn't supported by the new version of the mod?

**Comment by ToCraft** [comment]
Fixed as of b617ab9d69c1d063dbcc0c99dc9798658c8d84e0. The update is uploading rn
