### ISSUE TITLE
Multiple Crashes in differents conditions, with WoodWalkers 5.3.1

### ISSUE THREAD

**Issue by Dralaon** [ToCraft/woodwalkers-mod#136]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Woodwalkers version

5.3.1

### CraftedCore version

5.5

### Modloader version

0.16.5

### The latest.log file

[2024-10-02-1.log](https://github.com/user-attachments/files/17231395/2024-10-02-1.log)

### Issue description

Causes "Neruina - Ticking Entity Fixer" start killing Creepers and Spiders that will make the server crash.
Also causes crashes in the Player Entity when receiving some buffs from the mod SimplySkills abilities, such Stealth or Marksmanship. (not tested with others buffs types)

Working fine with WoodWalkers 5.2
Again, idk if is a incompatibility with something, have 300+ mods in it.

Logs dont point exactly to WoodWalkers i think, but this line repeats all over: com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 3 but got 2

### Steps to reproduce

Start the game
Open a World (with Neruina and/or SimplySkills)
Explore caves (or in the night) and wait for Creepers and Spiders to start spawning naturally, eventually Neruina will start spamming.
For SimplySkills, pick the Stealth ability (more easy to proc) and crouch, game will crash and a player's data reset will be needed.

**Comment by FullMetalMaster** [comment]
same for me Woodwalkers 5.3.1 doesnt wanna load at all

**Comment by FullMetalMaster** [comment]
https://pastebin.com/mFJ4ePBA

**Comment by Tikalian-coconut** [comment]
same issue as with the 5.3 version, it just crashes and doesn't load anything at all
forge 1.20.1
CraftedCore 5.5
Walkers 5.3.1
and loader saying "exit code 1"

**Comment by ToCraft** [comment]
Thanks for reporting, I'll upload a working version tomorrow, where I probably have to remove the ImmuntyTrait for now, bc I'm only on mobile rn so I can't write a real fix.

**Comment by ToCraft** [comment]
> same for me Woodwalkers 5.3.1 doesnt wanna load at all

You're encountering a different issue. Can you send me your crash log? I couldn't find any error in your attached game log

**Comment by ToCraft** [comment]
As I said before, I can't test it, but I just wrote a fix on my phone.
It's fixed as of 0b126fdde4f4bab3905c8e79096afeb410664bfc and it's uploading as walkers 5.3.2.
If it doesn't fix the issue, please let me know.
