### ISSUE TITLE
unexpected crash with exit code 1

### ISSUE THREAD

**Issue by Tikalian-coconut** [ToCraft/woodwalkers-mod#137]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

5.3.2

### CraftedCore version

5.5

### Modloader version

47.2.0

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17266605/latest.log)

### Issue description

unexpected crash on loading the game
exit code 1
am i supposed to guess why it crashed out of no information, seriously game
well that's the same as 5.2 and 5.2.1 versions (tested both and it crashes too)

### Steps to reproduce

start game
it just crashes and says nothing just, exit code 1

### Other

168 mods
and a custom mcreator mod, not sure if it could cause issue but better add it there :/

**Comment by jaeggr** [comment]
I'm experiencing this same crash as well on NeoForge 21.1.65, MC 1.21.1 (with Remorphed installed, but I disabled Remorphed and got the same result). Same log that just terminates while loading mixins.
[debug.log](https://github.com/user-attachments/files/17267615/debug.log)

**Comment by FullMetalMaster** [comment]
https://pastebin.com/f1GM4vCT
updated to 1.20.1-forge-5.3.2 still getting a crash

**Comment by seancrain** [comment]
I'm also encountering this crash, both in a modpack environment as well as with CraftedCore, Woodwalkers, and Remorphed installed on their own with no other mods. For me, it seems to be implicating the onModifyBreakingSpeedOnFlight(Z)Z method in the PlayerEntityMixin file.

**Comment by Zardo1** [comment]
Also having this issue- version 1.20.1 - forge 47.3.7

last lines in the log are below
[12:24:04] [main/WARN]: Error loading class: net/bettercombat/compatibility/CompatibilityFlags (java.lang.ClassNotFoundException: net.bettercombat.compatibility.CompatibilityFlags)
[12:24:04] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).

**Comment by ToCraft** [comment]
This issue is caused by some Refactoring by the Forge Project I wasn't aware of. That's way the mod currently modifies the block breaking speed using vanilla/fabric methods, that won't work bc Forge changed the minecraft code. I'll write a fixed version for forge/neoforge asap.
