### ISSUE TITLE
Incompatibility with CarryOn mod

### ISSUE THREAD

**Issue by SpookyEna** [ToCraft/woodwalkers-mod#138]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Woodwalkers version

5.3.2

### CraftedCore version

5.5

### Modloader version

0.16.5 Fabric Loader, 0.92.2 Fabric API

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17266984/latest.log)

### Issue description

When using the CarryOn mod with Woodwalkers installed, When picking up another player, rather than placing the Grabbed player in front of the Grabbing player, they are instead placed sort on top of but still inside of the Grabbing player. This is visually annoying but also causes problems due to the fact the hitboxes intersect and the Grabbing player cannot place the Grabbed player down themselves.

Installed Mods:

- Woodwalkers 5.3.2
- Carry On 2.1.2.7
- Carpet Mod 1.4.112+v230608
- CraftedCore 5.5
- Fabric API 0.92.2+1.20.1
- Mod Menu 7.2.2

Intended Result:
![image](https://github.com/user-attachments/assets/c01f2b30-a590-480b-b6e8-8ca5e44d1182)

Actual Result:
![image](https://github.com/user-attachments/assets/1d64dec5-7430-49a2-bf10-d6763e10cb42)

### Steps to reproduce

1. Start Game
2. Go to World (Whilst these steps use the Carpet Mod to spawn a fake player, this is present in a true multiplayer environment as well)
3. Spawn Player with Carpet Mod or have a player in a multiplayer world (ex: /player Alex spawn)
4. Attempt Pickup with CarryOn Mod
5. Player is picked up but is placed inside of the player model rather than in front like it is supposed to with CarryOn

**Comment by ToCraft** [comment]
fixed as of 2cc4696e9e75a319744f1672353a738f468021d2.
