### ISSUE TITLE
Mod support: Critters and Companions

### ISSUE THREAD

**Issue by Not-February** [ToCraft/woodwalkers-mod#143]
### Describe your idea, include images if necessary

I would love to see compatibility with [Critters and Companions](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions), which adds a handful of cute animals to the game with some unique functionality. I understand if you do not want to do some of the more complex cases mentioned here; even just having the simpler support for things like flight and having texture variants available for the creatures would be appreciated.

- Shima Enaga and Dragonfly can fly
- Jumping Spider can jump higher
- Ferrets can dig for treasure once every five minutes
- Red Panda scares away hostile mobs
- Otters swims quickly, can break open clams
- Dumbo Octopus can give an air bubble helmet to another player
- Leaf Insect dances when near a source of music like a jukebox

**Comment by ToCraft** [comment]
Hey! I'm sorry, but the mod you specified doesn't run on 1.21.2 minecraft and I don't plan to continue supporting old versions. However, you can add most of the features you specified yourself, using [data packs](https://github.com/ToCraft/woodwalkers-mod/wiki/Registering-Traits) as mentioned in the wiki.

**Comment by Not-February** [comment]
Oh, I'm sorry, I didn't realize you weren't supporting 1.20.1 anymore. Thanks for letting me know, I'll see what I can do with data packs

**Comment by Dragunsblood** [comment]
> Oh, I'm sorry, I didn't realize you weren't supporting 1.20.1 anymore. Thanks for letting me know, I'll see what I can do with data packs

hey, just curious if you ever got a data pack working? i also want to use critters and companions with this mod but can't get my own data pack working

**Comment by ToCraft** [comment]
Sure, data packs do work (actually, walkers handles some of it's trait logic with a built-in data pack).

**Comment by Not-February** [comment]
I never finished it. I was able to get some basic powers assigned to creatures but then got stuck on accurately formatting the creature variants and then got too busy to go back to it.

I'll give it another poke sometime soon

**Comment by Not-February** [comment]
[cnc_woodwalkers_support.zip](https://github.com/user-attachments/files/18121337/cnc_woodwalkers_support.zip)

Here's what I ended up with. It should support creature variant swapping and otherwise does the following:

- Otters swim quickly(but can't breathe underwater) and can use their ability to obtain a clam
- Jumping Spiders have a small passive jump boost and can use their ability to obtain a piece of silk
- Sea Bunnies are considered aquatic but can't swim
- Dumbo Octopuses are considered aquatic and should also apply water breathing to other players that are within ~3 blocks
- Red Pandas should scare away zombies, skeletons, creepers, spiders, strays, husks, and cave spiders. I'd recommend adding other entities/tags to the list tailored to your specific modpack as needed with an extra `"fearful_tags"` list in the "scares_hostile_mobs" trait file
- Dragonflies can fly
- Shima Enaga can fly and walk on powder snow(because they're small!), but are preyed on by cats and foxes. If you don't like the powdered snow tweak you can remove the file for it

I tried to mostly stay accurate to what the actual creatures do as best I can. I'm a little sad that I couldn't use an ability to check for a loot table or exchange a held item for another one - that would have been a perfect way to mimic ferret digging or opening clams, or even filling a bottle with sea bunny slime.


Leaf insects and ferrets don't really have anything special going on for them with this because I couldn't think of a way to do it well, but they do have their visual variants registered.
