### ISSUE TITLE
Missing Feature: Snow Powder freezing immunity

### ISSUE THREAD

**Issue by cyliamargatroid** [ToCraft/woodwalkers-mod#145]
I think It was missing one more thing
*Trait: "CantFreeze"

I was going to apply the immunity to snow to Maid Fairy (Touhou Little Maid), but it lacks the trait on how mobs cannot freeze. E.g.: Snow Golem, Polar Bear, Stray, Iceologer (Friends and Foes), Maid Fairy (Touhou Little Maid 1.13), Yeti (Twilight Forest)

**Comment by ToCraft** [comment]
Implemented as of 25efac266cfd8f63d32f52f295768ee4bc1ebd2d.
