### ISSUE TITLE
Polar Bear Left Arm Weirdness

### ISSUE THREAD

**Issue by Woopagadon17** [ToCraft/woodwalkers-mod#149]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

5.4

### CraftedCore version

5.5

### Modloader version

47.3.0

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17878115/latest.log)

### Issue description

When in second shape as a polar bear, the first person arm is positioned awkwardly when using the 'left arm' setting under skin settings.
![2024-11-22_18 23 41](https://github.com/user-attachments/assets/b88d9e9b-2a20-4c25-8d6d-d105fea361f1)
![2024-11-22_18 23 30](https://github.com/user-attachments/assets/01a3b29f-7e44-41f8-ab6b-36368037be05)

### Steps to reproduce

1.  Start Game
2.  Navigate to 'Skin Settings' and set 'Main Hand' to 'Left' under options.
3.  Load up a world and grab the second shape of a polar bear.
4. Switch to second shape and... well... yeah.

### Other

I understand it shows that one of the mods loaded is CPM or Custom Player Models,  I unloaded my model in game and tested the bug and it still showed up.  I can follow up with a re-creation without CPM if needed.

**Comment by ToCraft** [comment]
fixed as of 9725fc5b0a668218b09fe7f8a2eeea97fd7346e5
