### ISSUE TITLE
Squid has A Seizure

### ISSUE THREAD

**Issue by Yo-Snowpro** [ToCraft/woodwalkers-mod#152]
### Mod loader

Forge

### Minecraft version

1.21.3

### Remorphed version

5.0

### Woodwalkers version

6.0

### CraftedCore version

5.6

### Modloader version

Modrinth App v0.8.9

### The latest.log file

https://gist.github.com/Yo-Snowpro/bb9edd1f8e40bbd55413acd13796f6e7#file-gistfile1-txt

### Issue description

Basically, while on my modded world I killed a squid as a salmon then morphed into it cuz i thought it might be faster, and when i morphed and started swimming, the squid had a seizure. (it would be really funny if you keep it in somehow lol)

### Steps to reproduce

1. Start game
2. Go into a world (creative or survival)
3. Morph into squid (Optional kill squid if in survival)
4. Look like you need to get to the EMU asap

**Comment by ToCraft** [comment]
That's since squids have some very complicated custom animation properties. I won't be able to fix it anytime soon.

**Comment by Yo-Snowpro** [comment]
K at least ill get to see seizure :D
