### ISSUE TITLE
CantFreezeTrait needs a Backport (1.20.1, 1.21.1)

### ISSUE THREAD

**Issue by cyliamargatroid** [ToCraft/woodwalkers-mod#158]
### Describe your idea, include images if necessary

I'm happy that CantFreezeTrait was added, but I noticed that it lacked `CantFreezeTrait` on the recent update on Walkers mod on Minecraft 1.21.1.

**Comment by ToCraft** [comment]
Alright, I just backported it as of 57bf77ec0e4376b9cf6088dd420402e93736bd2b. Please note that I do not officially support versions older then 1.21.2 anymore, so it might take some time until I publish the backport. However, you can download the backport in the [GitHub Actions - Artifacts](https://github.com/ToCraft/woodwalkers-mod/actions/runs/12432583710#artifacts) section.
