### ISSUE TITLE
[Identity] Cat Suggestions

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/woodwalkers-mod#17]
Fix that Ocelots and Cats won't run from a player, shaped as a cat.

Original issue: https://github.com/Draylar/identity/issues/448

**Comment by Herobrine7707** [comment]
You could let creeper run away as a cat would be cool

**Comment by ToCraft** [comment]
> You could let creeper run away as a cat would be cool

implemented as of c8a7f9333b423e9029b925bbe8e190e7e617d6ca

**Comment by Natedogwoooof** [comment]
> > You could let creeper run away as a cat would be cool
> 
> implemented as of [c8a7f93](https://github.com/ToCraft/woodwalkers-mod/commit/c8a7f9333b423e9029b925bbe8e190e7e617d6ca)

did u implamit this one yet

**Comment by ToCraft** [comment]
This one requires to change not-changable values in mojangs code, but I'll implement it, when I got the time to do so.
