### ISSUE TITLE
[Identity] Polar Bear attacks, even if shaped as Polar Bear

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/woodwalkers-mod#21]
Original issue: https://github.com/Draylar/identity/issues/442

**Comment by ToCraft** [comment]
Implemented as of 3b90357b323d24bd1b40efd47c2b9ab3e24fd219

**Comment by Natedogwoooof** [comment]
> Implemented as of [3b90357](https://github.com/ToCraft/woodwalkers-mod/commit/3b90357b323d24bd1b40efd47c2b9ab3e24fd219)

uhh i meant they shouldnt attacvk you when you go near there cubs my bad they still attack me as a polarbear

**Comment by ToCraft** [comment]
finally fixed as of 22e0787a922ec239e2c6f88791934f28ae2e19fa
