### ISSUE TITLE
[Identity] Not all morphs that should have hands have hands 

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/woodwalkers-mod#25]
Add arms for horse, donkey, mule, zombie horse, skeleton horse, fox, wolf, strider, warden, allay, creeper, zoglin & hoglin

Original isuse: https://github.com/Draylar/identity/issues/433

**Comment by Natedogwoooof** [comment]
in the normal morph mod like ichuns they do thats wht i suggested this one on identity github

**Comment by ToCraft** [comment]
hmm.
Maybe I'll integrate it in v1.11.

**Comment by Natedogwoooof** [comment]
the ones that had hands in og morph that dont have them here are wolf and foxes and horses

**Comment by ToCraft** [comment]
I know this took way to long, but finally it's [implemented](9b849cdf8f41e4222c78b2be3cf04175e1ef3bb5)! 🥳🥳
