### ISSUE TITLE
Morph-like addon

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#26]
can i use this one and replace it with identty and have the mod be like normal identity cuzx this one has more patches thankyou

**Comment by ToCraft** [comment]
That should work, but you'd have to re-unlock your identity/2ndShape.
Furthermore, since my mod is lore-based, you're only able to unlock upto one identity/2ndShape.

**Comment by Natedogwoooof** [comment]
ah shoot ill just stick with normal identit, i know he dose other stuff but identity is missling alot of features and sadly he hasnt been takeing my suggestions into account when he dose update it

**Comment by Natedogwoooof** [comment]
just a suggestion maybe make a option thats off by default but if u turn it on it will make the mod like normal identity

**Comment by ToCraft** [comment]
Maybe I'll make an addon, which does that ;D

**Comment by ToCraft** [comment]
I just created a woodwalkers-addon, called "Remorphed" which does that :D
Here's the GitHub-Repository: https://github.com/ToCraft/remorphed

**Comment by Natedogwoooof** [comment]
nice thyankyou will try out tommarrow
