### ISSUE TITLE
Vex flying through walls

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/woodwalkers-mod#27]
A vanilla vex is able to fly through walls, maybe the player should, too. (Maybe some block-blacklist?)

**Comment by Natedogwoooof** [comment]
Another good way to balance this would be to make it so it uses more hunger

**Comment by ToCraft** [comment]
Implemented as of 77de7ed638799a106cd23c997a8205eac9bb08ac
I never thought this was that hard. ;D
