### ISSUE TITLE
cant aquire villager morph

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#32]
IDK if it's remorphed or wood walkers, but when I kill a villager I don't get the morph

Fabric, 1.20.2   
file:///home/nathaniel/Desktop/stuff%20mint/Minecraft%20stuff/instances/Identity%20Mod/.minecraft/logs/latest.log

**Comment by Natedogwoooof** [comment]
[latest.log](https://github.com/ToCraft/woodwalkers-mod/files/13720420/latest.log)

**Comment by Natedogwoooof** [comment]
same thing with wandering trader

**Comment by ToCraft** [comment]
It's not a bug. By default, villager, trader ans bosses are blacklisted. You could create a small datapack which revokes that. (I can create one for you, too, once I've got enough time today.)

**Comment by ToCraft** [comment]
[unlockVillagerTraderBoss.zip](https://github.com/ToCraft/woodwalkers-mod/files/13724253/unlockVillagerTraderBoss.zip)

Alright, this should work. If it doesn't, please let me know.
(Here's the official guide for datapacks: https://minecraft.wiki/w/Data_pack#Usage and here are values you can change in in the Woodwalkers-Mod with Datapacks: https://github.com/ToCraft/woodwalkers-mod/wiki/Datapacks

**Comment by ToCraft** [comment]
Alright, somehow this didn't work so I removed them from the blacklist again (as of 175b8bbcf824c5a292fddf88816f14001d56ab9b ) and I'll create an official datapack in the [wiki](https://github.com/ToCraft/woodwalkers-mod/wiki), which blacklists them for those who want that.
