### ISSUE TITLE
Crash when trying to join world

### ISSUE THREAD

**Issue by minecraftedleen** [ToCraft/woodwalkers-mod#35]
Crashes with exit code 1, like Identity mod.
I was using a modified version of identity mod so it wouldn't crash, but decided to try this mod out, but it crashes
(Different error now when trying to join world)

**Comment by minecraftedleen** [comment]
nevermind, I didn't install a required dependency

**Comment by minecraftedleen** [comment]
however it still crashed when I tried to join a world

**Comment by minecraftedleen** [comment]
[crash-2023-12-23_20.26.48-server.txt](https://github.com/ToCraft/woodwalkers-mod/files/13760601/crash-2023-12-23_20.26.48-server.txt)

**Comment by ToCraft** [comment]
This mod only crashes since you installed a wrong version of CraftedCore. Try 1.2.3 until Woodwalkers 12 is out.

**Comment by minecraftedleen** [comment]
unfortunately it seems that theres no 1.20.1 version of craftedcore 1.2.3

**Comment by ToCraft** [comment]
Oh, right. I removed it due to wrong tags but forgot to re-upload it to curseforge.
Nevertheless, here's the Modrinth-Link: https://modrinth.com/mod/crafted-core/version/1.20.1-forge-1.2.3
