### ISSUE TITLE
Incompatibility with mob battle mod? (1.20.1-1.2.3 forge)

### ISSUE THREAD

**Issue by minecraftedleen** [ToCraft/woodwalkers-mod#36]
Using mob battle mod I can get mobs to attack me on sight by joining a team and setting the mob to another team. However, when morphed as a hostile with walkers mod (or identity mod) I cannot get hostile mobs to attack me using mob battle mod

**Comment by ToCraft** [comment]
I'll take a look at this and try to fix it, but I don't know if I'll be able to fix it until Walkers 1.12...

**Comment by ToCraft** [comment]
You could change the value of `hostilesIgnoreHostileShapedPlayer` to `false` (in the config of woodwalkers).
Does this solve your issue?

**Comment by minecraftedleen** [comment]
no, that makes all hostile mobs attack me which isn't really what I want (I want to make it so that certain hostile mobs attack, like zombies for example) using the mob battle mod

**Comment by ToCraft** [comment]
Hmm. I'll try to write a fix.

**Comment by Natedogwoooof** [comment]
> Hmm. I'll try to write a fix.

i agree with op this feature would be cool

**Comment by ToCraft** [comment]
Finally, I added support for the MobBattleMod (as of 02fa1356a7ab8747284c37c3c09dbf452c2528b4). It will be available with Woodwalkers 3.1
