### ISSUE TITLE
Cave spiders 

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#37]
so in another mod called metamorph cave spiders could crawl through webs with no slowdown would this be possable? to make it so when your cave spider you have no slowdown from webs? also they should have abilty that lets you place down a cobweb as a cave spider

**Comment by ToCraft** [comment]
It should be, I'll try to implement it :D

**Comment by ToCraft** [comment]
implemented as of https://github.com/ToCraft/woodwalkers-mod/commit/85a3ba7f7254c792e54fdd78df29b8ebd8cea8ca
