### ISSUE TITLE
Ticking player exception

### ISSUE THREAD

**Issue by Omnimetatron** [ToCraft/woodwalkers-mod#39]
**Bug description**
Client crashes when a player enters water. Server then prevents entry.

**Game log:**
https://gist.github.com/Omnimetatron/a012440384929e09162424f76ed96e58

**Comment by ToCraft** [comment]
Alright, it looks like it's crashing while rendering entities which are in water...
I'll make a quick crash patch for this.

**Comment by ToCraft** [comment]
This should be fixed as of 1.12.1. :D
