### ISSUE TITLE
After leaving creative mode as a flying creature, flying no longer works ( forge and fabric and Neoforge1.20.1-1.20.4)

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#41]
hello when I saw the mod and tried it out I was thrilled, unfortunately there is a problem when I transform into any flying creature, e.g.
b into a bat and change the mode to surviva then I can no longer fly even though I have previously turned into a bat unfortunately the problem affects all flying creatures after the man died it works again

**Comment by ToCraft** [comment]
Oh, damn. Thanks for reporting, I'll do my best to fix this.

**Comment by ToCraft** [comment]
fixed as of df861917a55db64ec834fac2e94aba9246cffcc8
