### ISSUE TITLE
when loading with neoforge 1.20.4 it shows errors

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#42]
Hello, I tried to install the woodwalkers mod with neoforge, but every time it loaded it shows zero errors or something. In any case, you can't get into the menu to start the world. It doesn't crash, but it just loads with errors

**Comment by ToCraft** [comment]
Did you install Woodwalkers 1.12 or 1.12.1 and CraftedCore 1.2.3 or 1.3.1?

**Comment by ToCraft** [comment]
I fixed is as of the newest dev version of crafted core.
