### ISSUE TITLE
Quick suggestion; a whitelist, and black/whitelist commands?

### ISSUE THREAD

**Issue by onecreq** [ToCraft/woodwalkers-mod#43]
As with the blacklist that was added, I feel like it would be nice to add a toggleable whitelist config and a subsequent whitelist json. Commands for quickly and easily black/white-listing players would also be wonderful, just a simple /walkers whitelist/blacklist [username].

**Comment by ToCraft** [comment]
finally implemented as of ae74d6fe93afaad17f53b4fcac59a9fbfc359593
