### ISSUE TITLE
Compability with other mods

### ISSUE THREAD

**Issue by NikitaCherepov** [ToCraft/woodwalkers-mod#44]
Hi! I've tried some mods and noticed, there's no even opportunity to fly when you're using mobs from other mods. For example, crows from "Alex's mobs" can't even fly. I know, you can't add every mod on the Earth :) 
But is that possible to add aт ability to add/ edit features for modified/new creatures?

**Comment by ToCraft** [comment]
Yeah, it is possible to edit mobs which are able to fly via Datapacks.
Here's the wiki page: https://github.com/ToCraft/woodwalkers-mod/wiki/Datapacks. 
In case you're not familiar with datapacks, take a look at the [official minecraft wiki](https://minecraft.wiki/w/Data_pack) or watch some YouTube video how to create a custom one.

If you're patient and interested, you could also write me a list of modded mobs and what players morphed as such should be able to do, and I'll try to implement those into the next Woodwalkers-Version. Those two wiki pages show what mob abilities are available right now:
https://github.com/ToCraft/woodwalkers-mod/wiki/Datapacks
https://github.com/ToCraft/woodwalkers-mod/wiki/Abilities
but again, this is completely voluntary and don’t feel pressured to do anything. :D

**Comment by Tursiops-G** [comment]
For those us that are having issues with creating a functional Datapack, Could you please provide a downloadable Example Datapack that can be modified as needed? (like an example for a Bat, so that other Flying mobs could be easily added)? 
Thanks!

**Comment by Natedogwoooof** [comment]
maybe someday you should make a gui like ichuns
