### ISSUE TITLE
squid spazes out

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#46]
**Bug description**
squid spazes out in water dont know if its intended feature
**Game log:**
*Upload your game log as a spoiler. e.g.:*
<details>

 
file:///home/nathaniel/Desktop/stuff%20mint/Minecraft%20stuff/instances/Identity%20Mod/.minecraft/logs/latest.log
file:///home/nathaniel/Desktop/stuff%20mint/Minecraft%20stuff/instances/Identity%20Mod/.minecraft/screenshots/2024-01-05_17.13.38.png

**Comment by Natedogwoooof** [comment]
![2024-01-05_17 13 38](https://github.com/ToCraft/woodwalkers-mod/assets/109338104/2ebfffcc-9de2-4968-9c70-f7ae7071bfb8)

**Comment by Natedogwoooof** [comment]
log wouldnt post idk why

**Comment by ToCraft** [comment]
This is connected with #5, I'm working on a fix.

**Comment by ToCraft** [comment]
Original issue fixed as of https://github.com/ToCraft/woodwalkers-mod/issues/5#issuecomment-1913667986
