### ISSUE TITLE
weard horse head

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#47]
**Bug description**
horse head is tilted to the left sometimes only way to reverse it is to die
**Game log:**
*Upload your game log as a spoiler. e.g.:*
<details>
horse donkeys mules have weard heads
  
  ```log
![Uploading 2024-01-05_17.21.53.png…]()

**Comment by Natedogwoooof** [comment]
![2024-01-05_17 21 53](https://github.com/ToCraft/woodwalkers-mod/assets/109338104/542c6ef0-43f8-4dcb-820e-4af9993f8bf4)

**Comment by Natedogwoooof** [comment]
well no weard but the head is basiclly stuck

**Comment by ToCraft** [comment]
I'm not 100% sure (since this issue only happens seemingly random), but I might have been able to fix it as of 96024791bcf09e3ebf794c1c5584444433591f31
