### ISSUE TITLE
Axolotals and bees

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#48]
as an axolotal you should make topical fish pufferfish and cod salmon and squid glow-squid run from you and as those mobs axolotal will maybe attack you a=via rthere hunting phase if possable..also if you press t as a bee it should get angry and you can infilt poison as a bee, btw undead mobs arnt innmune to poison last time i checked so that needs to be added. when you attack as a bee it shoulods poison you also maybe.

**Comment by ToCraft** [comment]
What about bees only inflict poison when attacking and if they're angry?

**Comment by ToCraft** [comment]
Alright, I already implemented some of your ideas :D

- Bees get angry and inflict poison (as of 06f2719ec235c4dbcb28ad1d8408aeea809a75fa)
- Axolotl attack as-fish-shaped player (as of 06f2719ec235c4dbcb28ad1d8408aeea809a75fa)

**Comment by Natedogwoooof** [comment]
> Alright, I already implemented some of your ideas :D
> 
>     * Bees get angry and inflict poison (as of [06f2719](https://github.com/ToCraft/woodwalkers-mod/commit/06f2719ec235c4dbcb28ad1d8408aeea809a75fa))
> 
>     * Axolotl attack as-fish-shaped player (as of [06f2719](https://github.com/ToCraft/woodwalkers-mod/commit/06f2719ec235c4dbcb28ad1d8408aeea809a75fa))
> 
> 
> But are you sure fish should run from axolotl? I couldn't find something in the AI...

https://minecraft.wiki/w/Axolotl idk but i found it on here but its your choice i just found it on the mc wiki but i dont think they swim away from them.

**Comment by ToCraft** [comment]
I just went through the wiki and it says that pufferfish inflate when they see an axolotl, so I took a look at their AI and they always inflate when they see any non-water creature (or axolotl), so the player is naturally a "scary mob". :D

**Comment by ToCraft** [comment]
I just went through the wiki and it says that pufferfish inflate when they see a axolotl, so I took a look at their AI and they always inflate when they see any non-water creature (or axolotl), so the player is naturally a "scary mob". :D
