### ISSUE TITLE
Cat Sitting Tail issue

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#50]
**Bug description**
When you crouch as a cat the sitting animation works but the tail is bugged

</details>
this bug has been in the mod for a long time i remember it being there about a year and a half or 2 years ago

**Comment by Natedogwoooof** [comment]
![2024-01-06_11 20 10](https://github.com/ToCraft/woodwalkers-mod/assets/109338104/6b2aec89-7ccd-4e06-a9a8-689b29743188)

**Comment by Natedogwoooof** [comment]
dose the same with all the other varents

**Comment by Natedogwoooof** [comment]
when u fly in creative the sitting animation is correct like if your flying while crouching

**Comment by Natedogwoooof** [comment]
@ToCraft sorry for bothering you but is this fixable it's been a bug in the og identity mod for a long time also

**Comment by ToCraft** [comment]
I know, but I don't know what causes it yet and sadly, I'm busy with irl stuff for now, though I hope to fix it as soon as possible.

**Comment by Natedogwoooof** [comment]
OK i understand no rush

**Comment by ToCraft** [comment]
I now it definitely isn't beatiful but at least not bugged anymore...
I just changed the animation from "sitting" to "crouching" (as of 89402d0a3b1165384af560dd1a96b692548b6bfc). Here's an example:

![2024-02-28_17 19 42](https://github.com/ToCraft/woodwalkers-mod/assets/38883321/a1ef914a-f6e3-41ba-9fed-995b86649a93)
