### ISSUE TITLE
Witch heals raider morphs during raids

### ISSUE THREAD

**Issue by minecraftedleen** [ToCraft/woodwalkers-mod#51]
I’ve been using this mod for videos of myself raiding villages and I thought would be cool if witches threw splash potions of regen and healing at raider morphs during raids (if the witch isn’t attacking said morphed player)

**Comment by Natedogwoooof** [comment]
good idea but might be difficult to implant

**Comment by Natedogwoooof** [comment]
well sounds difficult

**Comment by ToCraft** [comment]
Alright, I just implemented this as of 80413e30ec3e6c7adf8b0474cced3db3aa55edf0. Please note that you have to hurt the witch once, so it'll start throwing potions at you.
