### ISSUE TITLE
Broken drowned model

### ISSUE THREAD

**Issue by minecraftedleen** [ToCraft/woodwalkers-mod#53]
![2024-01-16_18 20 33](https://github.com/ToCraft/woodwalkers-mod/assets/81533620/26420531-3725-45af-a5ee-30b6810afddc)

**Comment by Natedogwoooof** [comment]
same

**Comment by ToCraft** [comment]
fixed as of e7a171d408cfda210215be35226cbb9fabfbecd1. You might notice that the outer layer is not crouching while the main layer is. That's since the outer layer is missing an animation for it.

**Comment by ToCraft** [comment]
> Any idea when this fix might get released? Looking forward to it! And also the crafted core config fix I reported <3

Right now, I'm in a exam phase but I'll try to release the new updates in about 2-3 weeks (I still got some things on my To-Do-list)
