### ISSUE TITLE
Cats and Ocolots takeing fall damage

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#54]
**Bug description**
cats and ocolots and all no fall damage mobs are taking fall damage
[latest.log](https://github.com/ToCraft/woodwalkers-mod/files/13994441/latest.log)

**Comment by ToCraft** [comment]
Alright, I just tested it with a clean installation with the same loader and version as you and that issue didn't occur for me. Is it possible that one of your installed mods manipulates something in Minecraft's fall damage code?

**Comment by Natedogwoooof** [comment]
> Alright, I just tested it with a clean installation with the same loader and version as you and that issue didn't occur for me. Is it possible that one of your installed mods manipulates something in Minecraft's fall damage code?

Well to be fair I did build the mod with the Gradle correctly and then it started happening I'll make a second instance by copying my current one later and I'll replace those ones with the stock mod and I'll tell you if it happens

**Comment by Natedogwoooof** [comment]
Also try the classic remove some mods and then test it out again

**Comment by ToCraft** [comment]
Closed since it's not a bug in woodwalkers but in culprit, I think.
