### ISSUE TITLE
More suggestions

### ISSUE THREAD

**Issue by minecraftedleen** [ToCraft/woodwalkers-mod#56]
Enderman should attack endermite morph
Piglin alchemist morph from piglin proliferation should not be attacked by piglins (including alchemist)

**Comment by minecraftedleen** [comment]
also axolotls should attack drowned and guardian morph

**Comment by Natedogwoooof** [comment]
> Enderman should attack endermite morph Piglin alchemist morph from piglin proliferation should not be attacked by piglins (including alchemist)

1st one is aready implamitnted

**Comment by minecraftedleen** [comment]
I checked and the first one isnt implemented

**Comment by ToCraft** [comment]
> Piglin alchemist morph from piglin proliferation should not be attacked by piglins (including alchemist)
Implemented as of 8640d1d09f54076ba1636ed7450e5e91da00d372

**Comment by ToCraft** [comment]
> Enderman should attack endermite morph

implemented as of 4eb309ecdfcab7d1be1da9f987161f757ade0afb
