### ISSUE TITLE
Just some suggestions

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#60]
First is allays should also get slow fall ability,
As a Skeleton just like as a pillager you can ride ravanger. as a skeleton you should be able to ride skeleton horses.

Parrots
Not a big issue but there flapping animation is too fast. Also if you eat a cookie as a Parrot it should poison or instantly kill you.

Pufferfish
Idk if this is possible but just like when you use wolf ability you become hostile and when you use bee ability you become aggressive you should inflate as a pufferfish and when hitting your opponents you should inflict poison.

Snow Golums and Striders
Snow Golums Should get the varent where there Punken is off of them and When Striders are out of lava they should become the other varent if possible, and sheep's should get the Jeb and sheared varents.

Dolphin
Lastly as a Dolphin as a config option Dolphens should have a timer ot Smith to br out and in of water and maybe they should have an ability to gave all human shaped players Dolphin grace or have an ability to jump/ leap out of the water instead.

**Comment by ToCraft** [comment]
> First is allays should also get slow fall ability,

Implemented as of b82885816966c09b8b09ee01f002efafccb94b78

>  As a Skeleton just like as a pillager you can ride ravanger. as a skeleton you should be able to ride skeleton horses.

Implemented as of e2a654999243fda95373698adfd46582e39d427a

**Comment by Natedogwoooof** [comment]
> > First is allays should also get slow fall ability,
> 
> Implemented as of [b828858](https://github.com/ToCraft/woodwalkers-mod/commit/b82885816966c09b8b09ee01f002efafccb94b78)
> 
> > As a Skeleton just like as a pillager you can ride ravanger. as a skeleton you should be able to ride skeleton horses.
> 
> Implemented as of [e2a6549](https://github.com/ToCraft/woodwalkers-mod/commit/e2a654999243fda95373698adfd46582e39d427a). Right now, the skeleton horse must be tamed (only as Monster) but recognises the player, even if he's a "normal" player, since it's loyal to him :D
> 
> > and sheep's should get the Jeb and sheared varents.
> 
> I thought it be better, if a as-sheep-shaped player is able to drop his wool if he's holding shears, so I extended the sheep ability. Now you're able to drop your wool if you have shears in your main hand. You can regenerate it by eating. (e.g. grass. You eat it if you don't have shears in your main hand). Implemented as of [460854f](https://github.com/ToCraft/woodwalkers-mod/commit/460854f422a81d28e76032834946689cf0ec194e).
> 
> > Idk if this is possible but just like when you use wolf ability you become hostile and when you use bee ability you become aggressive you should inflate as a pufferfish and when hitting your opponents you should inflict poison.
> 
> Implemented as of [f181849](https://github.com/ToCraft/woodwalkers-mod/commit/f18184956ef91665366d46d1f5ec925893ff6c0d)

[13:13:29] [Server thread/ERROR]: Failed to use the "eating grass" ability!
java.lang.NoSuchFieldException: eatAnimationTick
	at java.lang.Class.getField(Class.java:2117) ~[?:?]
	at tocraft.walkers.ability.impl.GrassEaterAbility.eatGrass(GrassEaterAbility.java:19) ~[walkers-2.1-fabric.jar:?]
	at tocraft.walkers.ability.impl.SheepAbility.onUse(SheepAbility.java:20) ~[walkers-2.1-fabric.jar:?]
	at tocraft.walkers.ability.impl.SheepAbility.onUse(SheepAbility.java:10) ~[walkers-2.1-fabric.jar:?]
	at tocraft.walkers.network.ServerNetworking.lambda$registerUseAbilityPacketHandler$0(ServerNetworking.java:39) ~[walkers-2.1-fabric.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

i try to eat the grass to regen wool without shears in my main hand and this pops up

**Comment by ToCraft** [comment]
Are you using 1.20.2?

**Comment by Natedogwoooof** [comment]
> Are you using 1.20.2?

no why? has it not updated to 1.20.4? I thought you said it did

**Comment by Natedogwoooof** [comment]
[latest.log](https://github.com/ToCraft/woodwalkers-mod/files/14289362/latest.log)

**Comment by ToCraft** [comment]
> > Are you using 1.20.2?
> 
> no why? has it not updated to 1.20.4? I thought you said it did and you could use any 1.20.2 verson on 1.20.4?

Yeah, but it's still a development version and I haven't tested it on 1.20.4 yet.
It will work on 1.20.4 once I managed to fix this. Right now, you can only test this feature by running it as a development version (with `./gradlew [modloader]:runClient`).

**Comment by Natedogwoooof** [comment]
> > > Are you using 1.20.2?
> > 
> > 
> > no why? has it not updated to 1.20.4? I thought you said it did and you could use any 1.20.2 verson on 1.20.4?
> 
> Yeah, but it's still a development version and I haven't tested it on 1.20.4 yet. It will work on 1.20.4 once I managed to fix this. Right now, you can only test this feature by running it as a development version (with `./gradlew [modloader]:runClient`).

i downloaded it from the actions but i can do that with intelli J or jetbrains

**Comment by ToCraft** [comment]
> Yeah, but it's still a development version and I haven't tested it on 1.20.4 yet.
It will work on 1.20.4 once I managed to fix this. Right now, you can only test this feature by running it as a development version (with ./gradlew [modloader]:runClient).

Should be fixed as of 22e98d68822b336afd6f941151081488b34e2d2c

**Comment by ToCraft** [comment]
> Also if you eat a cookie as a Parrot it should poison or instantly kill you.

Implemented as of 6800df16abf3051c1f5ef303a1d42bc8b52f067d

> Not a big issue but there flapping animation is too fast. 

I know that's an issue, but I can't find the error in the code... I'll skip it for now.

**Comment by ToCraft** [comment]
> Snow Golums and Striders
Snow Golums Should get the varent where there Punken is off of them and When Striders are out of lava they should become the other varent if possible

Implemented as of a3f323be12912e50e1fbf58e7b7b7200c0ef5b79 and 20f7f6b5f9b324883a27479e9e0380ff6c0b1ce2

> maybe they should have an ability to gave all human shaped players Dolphin grace

Implemented as of 18a8795782046bc98ed242814985f60a345d1547. A as-dolphin-shaped player gives the nearest other player Dolphin's Grace with he's swimming from now on.
