### ISSUE TITLE
missing function for players as shulker forge fabric and neoforge 1.20.1 - 1.20.4

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#62]
Hi, I've noticed a bug in the mod for a while now when players can transform into shulkers. Players can't use any functions that shulkers normally have. Normally shulkers are known for shooting projectiles, which give players the levitation effect when hit. Unfortunately, this function is missing for players as shulkers

**Comment by ToCraft** [comment]
Implemented as of https://github.com/ToCraft/woodwalkers-mod/commit/9b2d2ff2119ec81157322973f4d9b04d51cff33b

**Comment by Natedogwoooof** [comment]
Boys it happened!!! Finally
