### ISSUE TITLE
players as drowned people look flawed forge fabric and neoforge Version 1.20.1 - 1.20.4

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#63]
hi, I tried the drowned one and found that it looked flawed. If the first texture worked normally, the second layer texture doesn't work. It looks like a baby and is bugged in the model

Here you can see what it currently looks like
![Minecraft NeoForge_ 1 20 4 - Einzelspieler 07 02 2024 14_42_28](https://github.com/ToCraft/woodwalkers-mod/assets/87422017/649a42ba-cdc7-4d58-872d-48915631d95f)

**Comment by ToCraft** [comment]
Already implemented as of e7a171d408cfda210215be35226cbb9fabfbecd1. It will be available with the next feature.
