### ISSUE TITLE
unlock one variant to use every

### ISSUE THREAD

**Issue by Herobrine7707** [ToCraft/woodwalkers-mod#64]
This is more of a functional suggestion than a bug I don't know what to call the title because there are some mobs with multiple textures in the game. My suggestion would be if players transform into one of the mobs e.g. cats, horses and various other creatures with multiple textures could choose the texture e.g.
b Assuming the player turns into a sheep and wants to turn into a pink or blue sheep, it would be nice if players could have the opportunity to do this using advanced commands

**Comment by ToCraft** [comment]
That's actually a neat idea! I thought about some kind of in-game menu to select the variant, but I don't know when I'll implement it.

**Comment by ToCraft** [comment]
implemented as of fd9755cb88740efa40cb2a3b9df88b655fad2ff0. It will be available with the next update.
