### ISSUE TITLE
Crash with Forge

### ISSUE THREAD

**Issue by Glamuu** [ToCraft/woodwalkers-mod#65]
Walkers (walkers) has failed to load correctly
java.lang.NoClassDefFoundError:
net/minecraftforge/event/entity/living/LivingBreatheEvent

**Comment by ToCraft** [comment]
You're using 1.20.1 Forge, right?

Please use Forge 47.2.0 or newer.

**Comment by ToCraft** [comment]
Feel free to reopen this if it still crashes.
