### ISSUE TITLE
[Question] A way to disable ability

### ISSUE THREAD

**Issue by Adam-Kay** [ToCraft/woodwalkers-mod#66]
Hi there, I'm currently trying to figure out a Morph-style mod to add to my modpack. I loved the original [Morph by iChun](https://www.curseforge.com/minecraft/mc-mods/morph) and was looking for something close to it for 1.18.2. I'm deliberating between [Budschie's Morph Mod](https://www.curseforge.com/minecraft/mc-mods/budschies-morph-mod), [Identity](https://www.curseforge.com/minecraft/mc-mods/identity), or this mod (Woodwalkers + ReMorphed).

I'd like to know if there is a way to disable certain abilities in the configuration. I am aware that you can change the cooldown, but let's say that I still wanted to allow players to change into a Blaze, but did not want them to be able to use the fireball ability that it comes with. Is this possible?

**Comment by ToCraft** [comment]
It isn't for now, but I like the idea of it, so I'll implement it with the next update. :D

**Comment by ToCraft** [comment]
Implemented as of b2e1dcc963618ea84c3081e9e9c9608e64688446

**Comment by ToCraft** [comment]
> Excellent, much appreciated! Will this make it into the 1.18.2 release, or will it only be for later MC versions?

I always try to support 1.18.2, 1.19.4, 1.20.1, 1.20.2+
Each update will be released for each mc version listed above ;D
