### ISSUE TITLE
Vector-based variants

### ISSUE THREAD

**Issue by Malwarechubb** [ToCraft/woodwalkers-mod#68]
Why Do Tropical Fish Have No Color? Not "No Color." But They Are Just White With Gray Markings.

**Comment by ToCraft** [comment]
Alright. I just scrolled through the issues at github.com/Draylar/identity and found this:
> Foxes, Villagers, Rabbits appearances will differ depending on which biome you equip the identity in

(from https://github.com/Draylar/identity/issues/138)

What do you think about it?

**Comment by Natedogwoooof** [comment]
> Alright. I just scrolled through the issues at github.com/Draylar/identity and found this:
> 
> > Foxes, Villagers, Rabbits appearances will differ depending on which biome you equip the identity in
> 
> (from [Draylar/identity#138](https://github.com/Draylar/identity/issues/138))
> 
> What do you think about it?

you made the mod so your choice but i would rather it stay like it is because thats how it is in metamorph and ichuns morph but i would like it as a config option if you do

**Comment by Natedogwoooof** [comment]
> > Player uuid? I don't really like that idea unless there's a way to change it in a game on single player
> 
> And if there'd be a config option to switch between randomly selected on world join (and then persistent) and each time you transform randomly selected?

yeah like a server config where you can have it be based on uuid or it randomlly changes in the morph menu

**Comment by ToCraft** [comment]
Alright, I just implemented random based variants for the tropical fish and the villager (and zombie villagers) as of 3bb9dd7443ea212d2babc4f197633e548287209b. I might rework it in the future.
