### ISSUE TITLE
[Identity] Many more sugesstions

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/woodwalkers-mod#69]
Original issue: https://github.com/Draylar/identity/issues/138

**Comment by minecraftedleen** [comment]
I like the patrol captain one, it would be nice if as a captain you could make illagers follow you

**Comment by ToCraft** [comment]
Just to keep track of this:

Still missing are:

- Instead of normal food, zombies should recover hunger points by dealing melee attacks to non-undead mobs, with 1 hunger point being filled for every damage point done
- Illager identities can equip the ominous banner to become a patrol captain, when the R key is pressed the horn sound plays, and patrol members are spawned in to ally the player
- Nocturnal & undead mobs can only sleep during the day
