### ISSUE TITLE
Crash when 3 or 4 players join

### ISSUE THREAD

**Issue by lemisset** [ToCraft/woodwalkers-mod#72]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

3.0

### CraftedCore version

3.1

### Modloader version

47.2

### The latest.log file

https://gist.github.com/lemisset/b7a2d1423e564ef845e7339b55de1447

### Issue description

I've created a custom modpack for my kids and I to play in and wanted to include remorphed. We installed crafting core and Woodwalkers as required.  It was working for a few days, but yesterday we updated and found that the game would crash when 3 or more people would join. We turned off remorphed and saw the same behavior.  We turned off Wood walkers and no longer had crashes.  The last log is attached.

### Steps to reproduce

Install Woodwalkers and crafted core with the latest versions.  Start a world and open it to LAN.  A 2nd player can join successfully.  A 3rd player may or may not crash the game. If a 3rd player doesn't crash, then the 4th player definitely will.

**Comment by ToCraft** [comment]
Fixed as of b8af74d0b75d4c973aee6df32668ae7825ee05a3. I'll publish a new version within a week.
