### ISSUE TITLE
Multiplayer crash w/ 3+ players

### ISSUE THREAD

**Issue by TWHalikon** [ToCraft/woodwalkers-mod#73]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

3.1

### CraftedCore version

3.1

### Modloader version

47.2.0

### The latest.log file

https://gist.github.com/TWHalikon/95c426e98c445a7d0e5a1bf93e09428c

### Issue description

Server crashes upon three players being in the same area at the same time.

### Steps to reproduce

1. Start game
2. Get on server with 3 or more people
3. Get three people together to result in the crash: "java.lang.IndexOutOfBoundsException: readerIndex(27) + length(1) exceeds writerIndex(27): UnpooledSlicedByteBuf(ridx: 27, widx: 27, cap: 27/27, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 27, cap: 27))"

**Comment by ToCraft** [comment]
Are you sure, all players use Walkers 3.1? The error says it's trying to load data that wasn't found and I've modified the network package wich causes your crash.

**Comment by TWHalikon** [comment]
All players were using Walkers 3.1, as the modpack required to join the server has the latest version of the mod installed. The issue stopped as soon as Walkers was removed.

**Comment by vmstan** [comment]
I have a similar setup: Forge 49.0.31, Minecraft 1.20.4, Walkers 3.1.

I don't see a server crash but when the third player tries to join it causes a client error that kicks one of the other players before to allow the new player to join.

**Comment by ToCraft** [comment]
Alright, I just managed to fix it as of 21a8daf18be2edc3606d0f53895951905a5490ef. I try to publish the next update until the weekend.
