### ISSUE TITLE
iron golums not throwing entitys into sky with bare hands

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#74]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Woodwalkers version

3.1

### CraftedCore version

3.1

### Modloader version

0.15.7

### The latest.log file

https://gist.github.com/Natedogwoooof/f041fec350b2d478dd8eacc0f46e06ed

### Issue description

in identity if you hit a mob as an iron golum it would fly into the air but it dosent anymore i dont know if this is a big or a feature, they dont fly into the air anymore.

### Steps to reproduce

start game
go into world
shape into iron golum
hiy any mob

### Other

also using remorphed 3.3

**Comment by ToCraft** [comment]
fixed as of 1c7e35eb73cbbb97b39245f2a7962c272782393c
