### ISSUE TITLE
Add "Unlockable" morphs

### ISSUE THREAD

**Issue by Syclusion** [ToCraft/woodwalkers-mod#76]
### Describe your idea, include images if necessary

Hi I am making a modpack around magic and druids, and am wondering if you could incorporate a datapack or config system / block or some kind of configurable event that will allow certain items to "unlock" specified transformations. For instance some kind of block or special item you throw in fire with a configured item (so you aren't checking every fire block when an item burns) that allows sacrificing said item to provide configured (via datapack or config) transformations. Like a wither skull unlocking wither skeleton etc etc.

**Comment by ToCraft** [comment]
As for now, your idea is too imprecise. (How should such a config option look like? It'd be a complete other unlocking mechanic and it'd be best to put it into an addon.)
But you could build a small redstone clock (if you don't want to mess around with Java), which runs a command, similar to this one:
`/execute as @a[nbt=!{Fire:-20s}] run walkers switchShape @s minecraft:blaze`
This will turn every burning player into a blaze.

If it is really necessary, I could also write you such an addon, but you'd have to specify the exact events, when the player unlocks a shape (e.g. What item should trigger it while burning?).
