### ISSUE TITLE
Varients Friends and foes and ability

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#77]
### Describe your idea, include images if necessary

sadly i couldn't figure out the data pack thing so i will suggest some, mooblooms if flowery mooblooms is installed with friends and foes should have variants, friendsandfoes:moobloom is namespace. mauler should get its variants too friendsandfoes:mauler, if possible they should hunt chickens, rabbits, frogs. if you're shaped as them. copper golums shouldn't take fall damage and should sink and breathe underwater and on land also. they should also have oxidized and non oxidized variants. namespace is friendsandfoes:copper_golem.  glares should be able to fly, namespace is friendsandfoes:glare, tuff golums should get their variants and be resistant to fall damage and sink underwater and breathe underwater friendsandfoes:tuff_golem. iceoligers should be hostile friendsandfoes:iceologer. lastly hovering infernos or wildfires should be fire resistant hostile and be able to fly and take damage in water. namespace is friendsandfoes:wildfire. also don't include the piorids oveously in namespaces.

**Comment by ToCraft** [comment]
> mooblooms if flowery mooblooms is installed with friends and foes should have variants, friendsandfoes:moobloom is namespace

implemented as of 971b1c93fdcb436cd2c9b25a29dce319d52d6893

> mauler should get its variants too friendsandfoes:mauler

implemented as of 5ac3ddbb168889d02b4b4e97c7602cba68362f77

> if possible they should hunt chickens, rabbits, frogs

implemented as of 23e19222ce7c7649c4c4a873b3830da006d2236e

> copper golums shouldn't take fall damage and should sink and breathe underwater and on land also

already implemented

> glares should be able to fly

already implemented

> they should also have oxidized and non oxidized variants.

implemented as of 3881787ff3819569d3848a909974612cd546776c

> tuff golums should get their variants

implemented as of f9a14c5167ab28b379ff41b6f5981b236b46c47b

> and be resistant to fall damage and sink underwater and breathe underwater friendsandfoes:tuff_golem

already implemented

>  iceoligers should be hostile friendsandfoes:iceologer

already implemented

>  lastly hovering infernos or wildfires should be fire resistant hostile and be able to fly and take damage in water. namespace is friendsandfoes:wildfire

implemented as of d731221de33e91fccfa2995fd65ec690876f77e3
