### ISSUE TITLE
Trader Lama Cooldown Config

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#78]
### Describe your idea, include images if necessary

would be nice if trader Lamas had a config for Their ability

**Comment by ToCraft** [comment]
Actually, you can already add it to the config, but yeah, I'll add it to the default config, too.

**Comment by ToCraft** [comment]
Implemented as of e0deb372d9261e961cf6cafabe972af93079d72c. Now, if you're morphed as any possible mob, the entity will be automatically added to the config with the default value, if it's not present (as of ee85175552f54ed85f9e91d40139785420a7c564).
