### ISSUE TITLE
Some More Suggestions

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#79]
### Describe your idea, include images if necessary

1.Ocelots should scare/chase chickens, and ocelots should attack players shaped as chicken.

2. rabbits are missing animations. wolves also don't attack players shaped as rabbits look at minecraft wiki at rabbits for more info, also stray cats should attack rabbits, as a rabbit you should get the ability to eat carrot crops if possable also sound on wiki, and if possible carrot crops that are fully grown or how minecraft wiki says matured

3. striders should be damaged by water and rain if that's not implemented areadey 

4. lastly if possable as a turtle you should be instantly killed by lightning and maybe have the ability to lay turtle eggs on land, every 300 seconds or 6000 game ticks

**Comment by ToCraft** [comment]
> Ocelots should scare/chase chickens, and ocelots should attack players shaped as chicken.

implemented as of f2add38b6ab270101a521d232db7ca22a262d753

> wolves also don't attack players shaped as rabbits look at minecraft wiki at rabbits for more info

implemented as of 418971667446168edf431f44a7df280494bbaea7

> striders should be damaged by water and rain if that's not implemented areadey

implemented as of 7712cfd9e2ec5ce10796c5d61cc853e39ef56f36
