### ISSUE TITLE
First Person Model Mod - Incompatibility

### ISSUE THREAD

**Issue by Kaede4Life** [ToCraft/woodwalkers-mod#80]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Woodwalkers version

3.2

### CraftedCore version

3.1.2

### Modloader version

47.1.101

### The latest.log file

https://gist.github.com/Kaede4Life/7413ee5fa2ba61fca9dc7d515de3187b

### Issue description

Game crashes in the middle of attempting to start up. This has occurred before, but did not crash on a second attempt to start the game, so I dismissed it as a fluke; however, it is now occurring every time.

### Steps to reproduce

1.) Attempt to start the game
2.) Game crashes during startup with "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

### Other

This is the specific crash report:

https://gist.github.com/Kaede4Life/11a8c86cd29a8800a9ee32ffae1f8ce2

EDIT: After some testing, the crash appears to be related to the Forge port of Origins: Classes, as it only crashes with it enabled. I am unsure whose end this issue lies on.

**Comment by ToCraft** [comment]
Alright, I'm not sure if this is fixable for me. In short, Woodwalkers tries to manipulate the shadows to be adjusted to your shape and, by the looks of it, Origins seems to simply delete the whole method (it can't be manipulated anymore).

**Comment by Kaede4Life** [comment]
It is strange how this does not crash when only the base Origins is installed, it only crashes when the Origins: Classes addon is installed alongside it. I figured the base would cause more issues. Regardless, thanks for the fast response. Bit of a bummer that it's a more deep-rooted issue. I may contact the people behind the port, but I doubt they would be willing to rework that entire section of code for this mod alone.

**Comment by ToCraft** [comment]
fixed as of 724d61223577f6c94f32ef851c75e65931c6c41c
