### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#81]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Woodwalkers version

3.2

### CraftedCore version

3.1.2

### Modloader version

0.15.7

### The latest.log file

https://gist.github.com/Natedogwoooof/0602492713c24b3e8e4a56e5a8f22c1a

### Issue description

first 2 suggestions i forgot rabbits should be able to walk on powdered snow. and maybe every so and so ticks/ seconds as a frog your should be abled to lay frogspawn very long cooldown. also biped mobs when they crouch their hitbox dosent change. Turtles can only brethe underwater when they should be abled to brethe on land and waterame with axlotals

### Steps to reproduce

none i think i explained it up there

**Comment by Natedogwoooof** [comment]
also piglins and hoglins shake when entering the nether from the over-world when they shouldn't in the nether

**Comment by ToCraft** [comment]
> first 2 suggestions i forgot rabbits should be able to walk on powdered snow

implemented as of 594baac50fedce01693a596ca1167c1aee3454bf

> Turtles can only brethe underwater when they should be abled to brethe on land

implemented as of cfca3e9a2797c7dd566a4e8a692c5b8e7fe4278e
