### ISSUE TITLE
Attacked by Aggressive Mobs Even If Disguised as One of Them

### ISSUE THREAD

**Issue by Magalia1020** [ToCraft/woodwalkers-mod#83]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Woodwalkers version

3.2

### CraftedCore version

3.2.1

### Modloader version

Fabric 0.15.7 & Fabric API 0.96.11

### The latest.log file

Other

### Issue description

I morphed into an Evoker and summoned several Vexes, and when I right-clicked while facing them, they suddenly turned against me and angered other illagers around me who stayed neutral before I did that. I tried to morph into other aggressive mobs such as a zombified piglin, right-clicked at other aggressive mobs and they attacked me as well.

### Steps to reproduce

I think that's all above.

### Other

[minecraft-exported-logs-2024-03-21T15-59-53.log](https://github.com/ToCraft/woodwalkers-mod/files/14691956/minecraft-exported-logs-2024-03-21T15-59-53.log)

**Comment by ToCraft** [comment]
That's actually a feature (by right-clicking, you can turn hostile mobs to attack you). I might add a config option to toggle it, though.

**Comment by Magalia1020** [comment]
> That's actually a feature (by right-clicking, you can turn hostile mobs to attack you). I might add a config option to toggle it, though.

oh okay
