### ISSUE TITLE
Mob effect in datapack crashing game

### ISSUE THREAD

**Issue by JacquePott** [ToCraft/woodwalkers-mod#84]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

4.1

### CraftedCore version

3.2.3

### Modloader version

47.2.0

### The latest.log file

https://gist.github.com/JacquePott/9c284ece13998b7d647a628ae01c2b86

### Issue description

This was tested alongside Remorphed and involves it's menu but I'm not sure if the root of the issue is from this mod or that one. My datapack adds a speed mobeffect to pigs. However, after unlocking the pig opening the morph menu crashes the game. Here is the relevant part of my datapack:
[pig.json](https://github.com/ToCraft/woodwalkers-mod/files/14765168/pig.json)

### Steps to reproduce

1. Start game.
2. Create new world with test datapack.
3. Use command to unlock pig morph.
4. Open morph menu.

**Comment by ToCraft** [comment]
Alright, I've tested it and it looks like an error in mojang's code (it only happens in 120.1, but the same codes works on 1.19.4 and 1.20.2+). I probably won't manage to fix this within the next weeks (I'm not at home...)

**Comment by ToCraft** [comment]
fixed as of c4b977e8d6e07c2ab697d51d96bde783e2328389.
