### ISSUE TITLE
Dolphin Field Access Transformation Error

### ISSUE THREAD

**Issue by DarkKinght98** [ToCraft/woodwalkers-mod#85]
### Mod loader

NeoForge

### Minecraft version

1.20.4

### Remorphed version

3.5

### Woodwalkers version

4.1

### CraftedCore version

3.2.3

### Modloader version

49.0.39

### The latest.log file

https://gist.github.com/DarkKinght98/d827ec853bbfcbfb554eb23a45ffbfde

### Issue description

after i killed a dolphin as a tropical fish when i tried to morph to the dolphin the game crashed and whenever i try to join the same world the game keeps crashing. 

### Steps to reproduce

1. start game 2. join the same world that the problem happened in 3. the game crashes

### Other

Remorphed and Woodwalkers are the mods that i think are causing the crash

**Comment by ToCraft** [comment]
Should be fixed as of 3d82a6ab6246326c7bb7a148e66cf7a6dfb74ae8. Feel free to reopen this issue, if the failure persists after Walkers 4.2
