### ISSUE TITLE
re add slowfall skill/ability

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#87]
### Describe your idea, include images if necessary

if there was a reason it was redmoved can you tell me it thanks

**Comment by ToCraft** [comment]
It *should* still be there, though it can be replaced with the MobEffectSkill.

**Comment by ToCraft** [comment]
Oh, I just found the issue. By creating the skill system, I forgot to add the the SlowFallingSkill for the chicken....

It's fixed as of e4526937a59bf4302deca002f8b40ac7a86bdb2c.
