### ISSUE TITLE
add abilities to mobs from other mods

### ISSUE THREAD

**Issue by FullMetalMaster** [ToCraft/woodwalkers-mod#88]
### Describe your idea, include images if necessary

examples would be breathing fire and flying with dragons from Ice and Fire

being able to fly with flying mobs from Alex's mobs

etc

**Comment by FullMetalMaster** [comment]
alexsmobs:bald_eagle = fly
alexsmobs:centipede =crawl on walls?
alexsmobs:crow = fly
alexsmobs:seagull = fly
alexsmobs:seal = swim
alexsmobs:shoebill = fly
alexsmobs:void_worm = fly
alexsmobs:mosquito = fly
iceandfire:fire/ICE/LIGHTING_dragon = FLY/fire
iceandfire:ghost = fly
iceandfire:pixie = fly
iceandfire:sea_serpent = swim

**Comment by ToCraft** [comment]
implemented as of c4678a472535ff7997b6c4152f0ddc766ca0237b
