### ISSUE TITLE
Changing shape kicks me out of the server

### ISSUE THREAD

**Issue by VillainousEater** [ToCraft/woodwalkers-mod#92]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

4.4.3

### CraftedCore version

4.2.2

### Modloader version

Forge 47.2.32

### The latest.log file

https://mclo.gs/x54SxPO

### Issue description

When I try to change shape, it kicks me out of the server with the exception:

> java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

I tried modded mob and then used commands to change to vanilla mob (wolf) and it happened again. This has been happening since the latest update to 4.4.3 :(

**Comment by ToCraft** [comment]
fixed as of 8090342bd54a88d6203ad9cfd123242e8e26a388
