### ISSUE TITLE
Server crash on seeing mobs

### ISSUE THREAD

**Issue by ArduFish123** [ToCraft/woodwalkers-mod#93]
### Mod loader

Fabric

### Minecraft version

1.20.6

### Woodwalkers version

4.4.3

### CraftedCore version

4.2.2

### Modloader version

0.5.11

### The latest.log file

Log: https://pastebin.com/Rm9WPuqe
Crash report: https://pastebin.com/ZApGXGWZ

### Issue description

Whenever I see some mobs while morphed, the server crashes

### Steps to reproduce

1. Start game
2. Join a server hosted on your computer with the mod
3. Morph
4. Look at a shulker

### Other

The crash occurs with: zombies, skeletons, shulkers etc.

**Comment by ToCraft** [comment]
fixed as of 8465fb69a2476ca7a1b9a833102b23b93ed07e23
