### ISSUE TITLE
woodwalkers broke in server bc of morph

### ISSUE THREAD

**Issue by FullMetalMaster** [ToCraft/woodwalkers-mod#94]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

walkers-4.4.3-forge.jar

### CraftedCore version

craftedcore-4.2.3-forge.jar

### Modloader version

47.2.32

### The latest.log file

https://pastebin.com/wxMLCaTY

### Issue description

just crashes you out of the server after morth seemingly random

**Comment by ToCraft** [comment]
It seems you're using Iris via Sinytra Connector. It's probably an issue with the connector, please report it to them.
