### ISSUE TITLE
Enderman doesn't have teleport

### ISSUE THREAD

**Issue by Kiptytude** [ToCraft/woodwalkers-mod#98]
### Mod loader

Fabric

### Minecraft version

1.20.6

### Woodwalkers version

4.5

### CraftedCore version

4.2.3

### Modloader version

0.15.11

### The latest.log file

[latest.log](https://github.com/user-attachments/files/15597178/latest.log)

### Issue description

The Enderman doesn't seem to have the enderman ability, as even the cooldown after pressing R doesn't match the config. I hear the same sounds I hear as a wolf when going angry. Essentially though, no combination of pressing/holding R or the mouse buttons produces a teleport.

### Steps to reproduce

After not being able to teleport on a friend's server after acquiring an enderman shape organically, I uninstalled all mods until only this and its dependencies were left, started a single-player server, used the / command that transforms me into an enderman directly (without setting it as my alternate shape) and tried a lot of clicking and pressing R. Then I repeated the same after changing the distance and cooldown a bit, and setting shapesEquipItems to false (thought maybe the human punch was overriding the mob ability).

### Other

Nothing is blacklisted.
[walkers.json](https://github.com/user-attachments/files/15597305/walkers.json)

**Comment by ToCraft** [comment]
Yeah, I'm aware of this issue and I've already written a fix. You can test with as of 4.5.1+build.1.
