### ISSUE TITLE
1st person animations w/ Better Combat broken on newest version

### ISSUE THREAD

**Issue by Jack-0-Spades** [ToCraft/woodwalkers-mod#99]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

4.5

### CraftedCore version

4.2.3

### Modloader version

Forge - 47.2.0

### The latest.log file

log too big to post

### Issue description

First person animations for weapons are broken on the latest version when loaded with better combat. 3rd person animations still work fine, but when swinging any weapon they just sort of bob in place from first person perspective.

**Comment by ToCraft** [comment]
fixed as of 9b8fd9edf6a0c129d87d0768e81f895146032992
